### ISSUE TITLE
Feature: Support auto column sizing

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#25]
This one is big.  And hard.  (At least it has been for me in past attempts at grid work.)

Basically, the idea is that columns will scale to fill the space allocated to the grid.  And they do it by ratio of the column sizes.  (So a column size of 50 would scale twice as fast as a column size of 25.)

But with that, you usually need to support max and min column size properties. (Meaning it will grow "no larger than" or shrink "no smaller than")

"The devil is in the details" on this one.  It gets hard the as screen is resized, etc.  But it helps the look of the grid.

**Comment by vegarringdal** [comment]
Yes, but atm the grid do not support any resizing after its created.
Its really because I need to set row size etc for resizing columns, sortable, and some other stuff.
Ofc this doesnt mean its impossible, just haven really seen much need of it
Or Im I missunderstanding where you are going?
The more you explain the better.
Added page up/down to the demo002 btw.
Great if you test that for bugs, that haveto be bugfree like its made before I start adding/modifying new stuff, like the feedback on doubleclick :-)

**Comment by Vaccano** [comment]
I was mostly referring to column widths.  Right now my grid has a lot of space that is not being used.  

I I could expand it to fit that space, but then the grid will be too big for those with smaller screens/resolutions.

It would be nice if it could adjust the columns to the size of the grid.

However, I don't need this feature now.  I was just logging it as a, "it would be nice eventually" feature.

**Comment by vegarringdal** [comment]
ok
Ill think about it, a min-size/max size could work as long as I dont have to think about resizing grid

**Comment by vegarringdal** [comment]
this might work out of the box if you do it right
In the config you need to add the "grid-context:myGrid"

inn the app you then do this:

```
  myCollection = [];
  myCurrentEntity = {};
  //super silly way of doing this, but I have 5 columns, and want them to be same size and 1/5 of screen size
  screenFift = window.screen.width/5;
  myGrid = {
    columnWidthArray:[this.screenFift,this.screenFift,this.screenFift,this.screenFift,this.screenFift]
  }

```

ofcorse you would haveto do a little more code if you want it to be better, but using the columnWidthArray will override whatever is written in the DOM
